import { init } from "loop.script";

var loop = init();
var startNode = "home";
var serverPrefix = "pserv-";
var hackScript = "hack.script";

function root(target) {
    if (!hasRootAccess(target)) return true;

    installBackdoor(target);

    return true;
}

loop(startNode, function (node) {
    if (node.indexOf(serverPrefix) >= 0) return false;

    // if (root(node) && !scriptRunning(hackScript, node)) {
    //     var numThreads = Math.floor(getServerMaxRam(node) / getScriptRam(hackScript));
    //     if (numThreads > 0)
    //         exec(hackScript, node, numThreads, node);
    // }
    print("rooting " + node);
    root(node);

    return true;
});